### ISSUE TITLE
[cpp] leetcode #442

### ISSUE THREAD

**Issue by aayush26** [aayush26/leetcode#28]
**Is your new leetcode problem solution has duplicate in the repository?**
A duplicate solution means that the programming language and the algorithm applied is the same.
If same algorithm but different programming languages, then the issue is valid and accepted.
If yes, please stop here and don't submit a new issue as it won't be accepted.

**Leetcode problem link**
https://leetcode.com/problems/find-all-duplicates-in-an-array/

**Comment by rpartha** [comment]
working on this
